export const LOGIN_CREDENTIALS = 'LOGIN_CREDENTIALS'

export const REQUEST_STARTED = 'REQUEST_STARTED'
export const REQUEST_SUCCESSS = 'REQUEST_SUCCESSS'
export const REQUEST_FAILED = 'REQUEST_FAILED'

export const LOGIN_SUCCESSS = 'LOGIN_SUCCESSS'

export const CRICKETER_DETAILS = 'CRICKETER_DETAILS'
export const UPDATED_CRICKETER_DATA = 'UPDATED_CRICKETER_DATA'
export const LOGGED_IN = 'LOGGED_IN'
export const LOGGED_OUT = 'LOGGED_OUT'

export const SINGLE_CRICKETER_DETAILS = 'SINGLE_CRICKETER_DETAILS'
